### ISSUE TITLE
Regression between 20.5.31.1 and 20.12.7.4 (Test_StructInstanceByRef)

### ISSUE THREAD

**Issue by pardeike** [MonoMod/MonoMod.Common#11]
Regression between 20.5.31.1 and 20.12.7.4. The following test hangs and never completes with the new version in Release build (both versions pass in Debug build of Harmony):

```cs
[Test]
public void Test_StructInstanceByRef()
{
    var originalClass = typeof(Assets.Struct2);
    Assert.NotNull(originalClass);
    var originalMethod = originalClass.GetMethod("TestMethod");
    Assert.NotNull(originalMethod);

    var patchClass = typeof(Assets.Struct2Patch);

    Assert.NotNull(patchClass);
    var postfix = patchClass.GetMethod("Postfix");
    Assert.NotNull(postfix);

    var harmonyInstance = new Harmony("test");
    Assert.NotNull(harmonyInstance);

    var result = harmonyInstance.Patch(originalMethod, null, new HarmonyMethod(postfix));
    Assert.NotNull(result);

    var instance = new Assets.Struct2() { s = "before" };
    instance.TestMethod("original");
    Assert.AreEqual("patched", instance.s);
}

public struct Struct2
{
    public string s;

    [MethodImpl(MethodImplOptions.NoInlining)]
    public void TestMethod(string val)
    {
        s = val;
    }
}

public class Struct2Patch
{
    public static void Postfix(ref Struct2 __instance)
    {
        __instance.s = "patched";
    }
}
```

Seems 64bit x86 is affected as my Azure tests for other architectures pass just fine: https://dev.azure.com/pardeike/Harmony/_build/results?buildId=1073&view=results

**Comment by nike4613** [comment]
What runtime is this failing on?

**Comment by pardeike** [comment]
Just added the info. You can see it in the Azure Config and I tested this locally on my 64Bit Win10 dev machine.

**Comment by nike4613** [comment]
Can you replicate the same behaviour using MonoMod's detours?

**Comment by pardeike** [comment]
Double checked. Everything below net core 3.0 stalls.

**Comment by pardeike** [comment]
I am unfamiliar with MonoMod's detours since I only maintain Harmony.

**Comment by pardeike** [comment]
GetMethodStart in MMC hangs on this method (release build):
```cs
public struct Struct2
{
    public string s;
    [MethodImpl(MethodImplOptions.NoInlining)]
    public void TestMethod(string val)
    {
        s = val;
    }
}
```
but works fine with this instead:
```cs
public void TestMethod(string val)
{
    try
    {
        s = val;
    }
    catch (Exception e)
    {
        throw new Exception("" + e);
    }
}
```

**Comment by 0x0ade** [comment]
I've added a new test to MonoMod to replicate and further track this on our end: https://github.com/MonoMod/MonoMod/commit/58c6079e167f9a587e0175c05f95849883317f87

Thanks to @pardeike, we managed to identify the hanging code:

https://github.com/MonoMod/MonoMod.Common/blob/563f9516b7e69f16433e24f532827d64913f5bcf/RuntimeDetour/Platforms/Runtime/DetourRuntimeNETPlatform.cs#L188-L196

![Visual Studio debugger screenshot](https://cdn.discordapp.com/attachments/674571535570305060/786270408277360650/unknown.png)
