### ISSUE TITLE
Please provide a strong-named version

### ISSUE THREAD

**Issue by dauthleikr** [MonoMod/MonoMod.Common#38]
Hi,

I am trying to use Harmony in a project where strong-naming is unfortunately required. While I can build harmony myself, I am unsure how to strong-name MonoMod.Common (a dependency of harmony, nuget package), since the description says to "not even try to" build it as a library (but that is how it is consumed by harmony). Could you maybe provide a strong-named version for nuget, or give me a hint on how to proceed? Thanks :) 

Btw: StrongNamer does not work for .net framework Harmony for some reason.

**Comment by pardeike** [comment]
Microsoft recommends to not sign public open source libraries because there is little use in having the private key checked into source control and there is no other place because the whole lib is public. 

What you do instead is to sign the library yourself.

**Comment by pardeike** [comment]
Also make sure you are aware that Harmony v2.3 no longer packs its dependencies into the harmony binary.
