### ISSUE TITLE
Are there any plans in place for upgrading to net8 when it comes out?

### ISSUE THREAD

**Issue by JROBOTO** [MonoMod/MonoMod.Common#40]
I Consume the Harmony library which uses this but ideally would like to upgrade to net7 (or net8 when it comes out). Is there a plan, to upgrade to one or both of these versions in the near future?

**Comment by nike4613** [comment]
MonoMod currently supports .NET 7. I'd like to already have .NET 8 support, but I have had a distinct lack of time to work on it, so that's much more likely to happen once .NET 8 reaches GA.

**Comment by pardeike** [comment]
I think it's just fair to wait for GA

**Comment by JROBOTO** [comment]
Ok, thanks
